export { default as NavbarAdmin } from "./Navbar";
export { default as AdminInfo } from "./AdminInfo";
export { default as Events } from "./Events";
export { default as Gallery } from "./Gallery";
export { default as Services } from "./Services";
export { default as Tours } from "./Tours";
export { default as OrderTour } from "./OrderTour";
export { default as OrderServic } from "./OrderServic";
export { default as OrderEvent } from "./OrderEvent";
